-- Clear existing sample growth plays if any
DELETE FROM public.growth_plays;

-- Insert all growth plays from the BlueConic Growth Plays spreadsheet
INSERT INTO public.growth_plays (
  name,
  journey_stage,
  jtbd,
  where_to_activate,
  features_to_use,
  primary_success_metric,
  kpis,
  complexity,
  risk_mitigation,
  deliverables,
  prerequisites,
  time_to_value,
  is_active
) VALUES
(
  'Lookalike & High-Value Prospect Expansion',
  'Prospecting & Awareness',
  'When I need to grow my customer base efficiently, I want to find and target new audiences that behave like my best customers so I can reduce acquisition costs and scale revenue from high-value segments',
  'Ads, Display, Social, CRM',
  'Insight, Listener, Connection, Segmentation, AIWB',
  'Incremental Revenue Lift (revenue lift per $ of spend, driven by BlueConic optimized segments) - Definition: additional revenue generated per $ of spend when BlueConic-orchestrated lookalike segments/audiences are used, compared to: 1. the same spend through native platform lookalikes or 2. the brand''s historical acquisition baseline',
  'Lookalike performance lift (i.e CTR, CAC, ROAS, CPA, AOV etc.)',
  'There are no pre-trained lookalike models available, so the customer will either need to bring their own model (BYOM) or have AI Workbench (AIWB) notebooks developed to train new models. This requires a thorough discovery phase to define hypotheses, features, conversion events, targeting rules, control group size, and other key parameters. Once development begins, the model must be trained and allowed to converge before it can deliver optimal results - a process that may take time and impact overall timelines. There is also the maintenance aspect to this - who is responsible for providing support and maintaining these customer-trained models?',
  'Develop templatized solutions for the most common "Next Best" models (action/offer/channel). By defining a standardized framework we can significantly reduce the amount of time spent on the discovery phase. In practice, this means teams can quickly configure, train and deploy predictive models, rather than starting from scratch each time. This approach improves efficiency, accelerates time to value, and ensures greater consistency and quality across implementations.',
  'Templatized AIWB notebooks for training lookalike, audience selection, next best channel selection models. Predefined feature sets (e.g., recency, frequency, average order value, engagement metrics, channel affinity) and hypothesis scaffolds that teams can customize. Standardized output segments, e.g. "high-value lookalike prospects". Standardized customer data schema and Listeners setup designed for acquisition and lookalike use cases - including key attributes like: purchase history, engagement frequency, conversion events, channel touchpoints. Purpose-built Connections to common ecommerce platforms (Shopify, Magento, Salesforce Commerce Cloud) for transactional syncs. OOTB Dashboards for tracking ROAS, CAC, and conversion lift vs. platform-based lookalikes, etc.',
  'Data readiness - First-party behavioral and transactional data. Feature/hypothesis alignment for lookalike modeling. Minimum volume of known customers (e.g., 5K–10K active buyers) to train a meaningful lookalike model. Access to advertising platforms where modeled audiences can be activated. Clear understanding of business objective, success metrics',
  'Discovery: 2 wks, Implementation: 4 wks (AIWB notebook to train lookalike models), Go-Live: 1 wk, Total: ~7 wks. Future: OOTB AIWB notebook to train Lookalike models + standardized data schema can potentially reduce TTV to <4 wks',
  true
),
(
  'Intent-Based Media Targeting',
  'Prospecting & Awareness',
  'When I invest in paid media, I want to identify and prioritize audiences that show genuine intent so I can optimize spend toward buyers who are most likely to convert.',
  'Social, Ads, Display, CTV, Paid Search, DSP',
  'Connection, Segmentation, Listener, AIWB',
  'Incremental Media Efficiency: The incremental conversions or revenue per paid media impression, driven by BlueConic''s intent activation vs alternatives. Definition: % improvement in conversion or revenue yield per media impression or $ achieved when BlueConic''s intent signals are used to drive media activation or suppression, compared to 1) the same campaign without BlueConic intent data or 2) the brand''s historical baseline for targeting',
  'CPM, CPA, CPL, CPC, ROAS',
  'No pre-trained NBA models available for predicting intention.',
  'Templatized solutions that include pre-defined CDP Listener setups and example segment definitions, intent prediction model. Internal team or agency resource dedicated to building and testing Experiences.',
  'Templatized solutions that include Experience templates, pre-defined CDP Listener setups and example segment definitions, NBA model. Internal team or agency resource dedicated to building and testing Experiences.',
  'Data readiness - consistent website tagging to support capturing intent. Feature/hypotheses alignment for NBA model. Experience ownership: access to front-end / design support for styling and layout. Clear understanding of business objective, success metrics. Access to advertising platforms where intent-based audiences can be activated',
  'Discovery: 2 wks, Implementation: 4 wks (AIWB notebook to train intent prediction model), Go-Live: 1 wk, Total: ~7 wks. Future: OOTB AIWB notebook to train intent prediction models + standardized data schema can potentially reduce TTV to <4 wks',
  true
),
(
  'Engagement → Identity Conversion',
  'Engagement to Identity',
  'When visitors engage with my content anonymously, I want to turn that engagement into identity capture so I can connect behavior to individuals and personalize future experiences.',
  'Web',
  'Experience (XP), Dialogue, Listeners, Profile Merging (Identity Resolution), Consent Management',
  'Incremental Identity Conversion Rate: % increase in new, consented, first party identities created when BlueConic''s features are used, compared to the brand''s historical/baseline rate.',
  'Known-to-anonymous ratio, Profile Merge rate, Consent Capture Rate',
  'The number and type of Experiences (XPs) is the primary risk factor: our standard onboarding model for Experiences is "self-onboarding with guidance", meaning that we provide training but the customer team is responsible for building, configuring, and launching the Experiences themselves. While this model promotes customer independence and scalability, it introduces variability in time-to-launch and overall impact depending on the complexity of the Experiences (simple quiz vs outcome-based vs DPF). Depending on the type/complexity of the Experience, it can take up to 45 days for a customer to launch their first Experience.',
  'Templatized solutions that include Experience templates, pre-defined CDP Listener setups. Internal team or agency resource dedicated to building and testing Experiences.',
  'Pre-configured, click-to-clone templates for common Experience types (quiz, survey, product matcher, lead capture). Predefined Listeners and CDP/XP connection for capturing intent and first-party data.',
  'Data readiness - consistent website tagging to support capturing intent/behaviour/interest. Experience ownership: access to front-end / design support for customizing styling and layout. Clear understanding of business objective, success metrics.',
  'Discovery: 1 wks, Implementation: 4 wks (2 Experiences, customer-built), Go-Live: 1 wk, Total: ~6 wks. Future: AI Experience Builder can potentially reduce Implementation time, no data available yet to estimate impact',
  true
),
(
  'Progressive Identity & Preference Building',
  'Engagement to Identity',
  'When customers start interacting with my brand, I want to capture their preferences and consent gradually so I can personalize responsibly and strengthen trust over time.',
  'Web, Email',
  'Experience (XP), Dialogue, AIWB, Listeners, Consent Management',
  'Incremental Profile Enrichment Rate: the % increase in known, declared, and consented profile attributes captured per known profile over time, when BlueConic''s progressive profiling, interactive experiences, and consent management are used versus the brand''s baseline approach',
  'AOV, Conversion Rate, Click Through Rate, Completion rate, Opt-in rate, Data Depth per profile',
  'The number and type of Experiences (XPs) is the primary risk factor. No pre-trained NBA models available for picking best content to serve, e.g. consent dialog, preference center, quiz, etc.',
  'Templatized solutions that include Experience templates, pre-defined CDP Listener setups. Internal team or agency resource dedicated to building and testing Experiences.',
  'Templatized AIWB notebooks for training the NBA model, standardized feature sets, data model, data collection, dashboard. Pre-configured, click-to-clone templates for common Experience types (quiz, survey, product matcher, lead capture). Predefined Listeners and CDP/XP connection for capturing intent and first-party data.',
  'Data readiness - consistent website tagging to support capturing intent/behaviour/interest. Feature/hypotheses alignment for NBA model. Experience ownership: access to front-end / design support for customizing styling and layout. Clear understanding of business objective, success metrics.',
  'Initial implementation (no NBA): Discovery: 1 wks, Implementation: 4 wks (2 Experiences, customer-built), Go-Live: 1 wk, Total: ~6 wks. Future: AI Experience Builder can potentially reduce Implementation time. NBA add-on: Discovery: 2 wks, Implementation: 4 wks, Go-Live: 1 wk, Total: ~7 wks. Future: OOTB AIWB notebooks to train NBA models can potentially reduce TTV for the NBA-addon to <4 wks.',
  true
),
(
  'First-Purchase Acceleration',
  'Conversion',
  'When a prospect shows interest but hasn''t purchased yet, I want to personalize the next step in their journey so I can shorten the time-to-first-purchase and improve conversion rates.',
  'Web, QR Code, (Web) Push, Ad Platforms, any channel that doesn''t require PII',
  'Product Recommendations, XP, Dialogue, Listeners, AIWB',
  'Time to first purchase reduction: % reduction in the average # of days or interactions it takes for a prospect to make their first purchase, compared to historical or control baseline. This can be determined from the time the brand "saw" the prospect for the first time to when they made their first purchase.',
  'Conversion Rate, Time to first purchase, AOV',
  'No pre-trained models available for discount sensitivity, best channel to trigger message, optimal timing. Product store limits - can only store up to 20k items. Number of product recommendation dialogues - need to decide on whether to include the recommendation Dialogue build in the onboarding or to push ownership to the customer. Either way - availability of copy/styling can cause delay.',
  'Templatized solutions for browse abandonment and the most common models (discount vs reminder, timing, best channel) to support targeting abandoners in the most optimal way. Internal team or agency resource dedicated to building and testing Product Recommendation Dialogues.',
  'Agentic-based Next Best Offer model support in recommendations. Increase limit on number of content/product store items. Templatized AIWB notebooks for training discount sensitivity, next best channel, optimal timing models. Standardized feature sets, data model, data collection, dashboard. Pre-configured, click-to-clone templates for Product Recommendation Dialogues. Purpose-built Connections to common ecommerce platforms (Shopify, Magento, Salesforce Commerce Cloud) for transactional and product data sync. Pre-configured Listeners to pick up on browse abandonment',
  'Data readiness - consistent website tagging to support capturing product data or having a product feed available on SFTP. Dialogue ownership: access to front-end / design support for customizing styling and layout of recommendation units. Clear understanding of product store limits, business objective, success metrics.',
  'Initial implementation (no NBA): Discovery: 1 wks, Implementation: 3 wks (3 Dialogues, PS-built), Go-Live: 1 wk, Total: ~5 wks. NBA add-on: Discovery: 2 wks, Implementation: 4 wks, Go-Live: 1 wk, Total: ~7 wks. Future: OOTB AIWB notebooks to train NBA models can potentially reduce TTV for the NBA-addon to <4 wks.',
  true
),
(
  'Cart Abandonment Recovery',
  'Conversion',
  'When shoppers leave items in their cart, I want to re-engage them with timely, context-aware reminders or offers so I can recover lost revenue and protect margins.',
  'Web, Social, Ads, Display, Email, Mobile App, (Web) Push',
  'Dialogues, Connection, Product Recommendations, Product Store',
  'Incremental cart recovery revenue: Incremental revenue recovered from abandoned carts when BlueConic''s cross channel, consent aware recovery activations are used, compared to the brand''s historical baseline or control group',
  'Conversion Rate, Click Through Rate, CPM, CPA, CPL, AOV, RFM, CLV, Revenue, Recovery Rate, Lost Revenue Reclaimed',
  'Number of cart recovery dialogues - need to decide on whether to include the Dialogue build in the onboarding or to push ownership to the customer. Either way - availability of copy/styling can cause delay.',
  'Internal team or agency resource dedicated to building and testing Dialogues.',
  'Pre-configured, click-to-clone templates for Cart Recovery Dialogues. Purpose-built Connections to common ecommerce platforms (Shopify, Magento, Salesforce Commerce Cloud) for product data sync.',
  'Data readiness - exposure of cart behaviour events on the websites (add-to-cart, cart-update, order). Dialogue ownership: access to front-end / design support for customizing styling and layout of cart recovery dialogues. Clear understanding of business objective, success metrics.',
  'Discovery: 1 wk, Implementation: 3 wks (2 Dialogues, PS-built), Go-Live: 1 wk, Total: ~5 wks.',
  true
),
(
  'AI-Powered Branded Shopping Assistant',
  'Conversion',
  'When customers are browsing products, I want to provide conversational, personalized guidance so I can increase conversion and differentiate the brand experience.',
  'Web',
  'VWAM (if embedded in CDP: Product Store?)',
  'Incremental Conversion Value: The % uplift in revenue per visitor session (driven by increased conversion rate and/or AOV) when the shopping assistant is active, compared to a baseline without it',
  'Conversion rate, Revenue, AOV, Engagement Rate',
  'TBD',
  'TBD',
  'Potential for VWAM integration in CDP',
  'TBD',
  'TBD',
  true
),
(
  'Personalized Basket Expansion',
  'Post Purchase Growth',
  'When customers are shopping or checking out, I want to recommend personalized bundles or add-ons so I can increase average order value and customer satisfaction.',
  'Web, Email, Mobile app',
  'Dialogue, Connection, Product Recommendations, AIWB',
  'Incremental AOV: % uplift in average order value (AOV) achieved when BlueConic''s personalized add-on and upsell recommendations are active, compared to a baseline without it or control group',
  'AOV, Bundle Conversion',
  'No pre-trained models available for next best product (NBP) or complementary items/product bundles. Product store limits - can only store up to 20k items. Number of product recommendation dialogues and emails - need to decide on whether to include the recommendation Dialogue and email build in the onboarding or to push ownership to the customer. Either way - availability of copy/styling can cause delay.',
  'Templatized solutions for the most common models (NBP, bundling). Internal team or agency resource dedicated to building and testing Product Recommendation Dialogues.',
  'Agentic-based Next Best Offer model support in recommendations. Increase limit on number of content/product store items. Templatized AIWB notebooks for training models to predict next best product (NBP) or complementary item likelihoods. Standardized feature sets, data model, data collection, dashboard. Pre-configured, click-to-clone templates for Product Recommendation Dialogues and Emails, e.g. Cross-sell carousels ("Complete the Look"), personalized bundles at checkout ("Add these for 20% off"), dynamic recommendations in product detail pages. Standardized customer data schema and Listeners/Connections setup designed for product upsell use cases.',
  'Data readiness - consistent website tagging to support capturing product data or having a product feed available on SFTP. Dialogue ownership: access to front-end / design support for customizing styling and layout of recommendation units. Feature/hypotheses alignment & Modeling Readiness for NBP model - defined product categories, known conversion events, and sufficient transaction data. Clear understanding of product store limits, business objective, success metrics.',
  'Discovery: 2 wks, Implementation: 6 wks (AIWB notebook for model training, 2 Dialogues - PS-built), Go-Live: 1 wk, Total: ~9 wks. Future: OOTB AIWB notebook to train recommendation models + standardized data schema can potentially reduce TTV to <4 wks (Discovery and Go-Live not impacted)',
  true
),
(
  'Churn Prediction & Winback',
  'Retention',
  'When customer engagement starts declining, I want to detect early signals and trigger personalized winback actions so I can retain revenue and reduce reacquisition costs.',
  'Web, App Push, Mobile App, SMS/Whatsapp/Messages, Email, Ads, Social, Display',
  'Experience (XP), Dialogue, Connection, AIWB, Listeners, Segments',
  'Incremental Reactivation Revenue: Additional revenue generated from recently inactive customers who re-engaged or made a new purchase because of BlueConic''s agentic orchestration, compared to a historical or control group baseline',
  'Completion rate, Lead capture rate, Click Through Rate, Conversion Rate, LTV, Retention Rate',
  'No pre-trained models available for churn prediction. Number of Dialogues/Experiences - need to decide on whether to include the Dialogue build in the onboarding or to push ownership to the customer. Either way - availability of copy/styling can cause delay.',
  'Templatized solution for churn predication with configurable risk tiers (high, medium, low). Internal team or agency resource dedicated to building and testing Product Recommendation Dialogues.',
  'Templatized AIWB notebook for training churn prediction model. Standardized feature sets, data model, data collection, dashboard. Pre-configured, click-to-clone templates for Winback Dialogues/Experiences, e.g. "We miss you" messages personalized to product or category interest, exclusive reactivation offers based on previous purchase history, win-back surveys to capture reasons for inactivity. Standardized customer data schema and Listeners setup designed for re/upsell use cases. Purpose-built Connections to common ecommerce platforms (Shopify, Magento, Salesforce Commerce Cloud) for transactional and product data sync.',
  'Data readiness - First-party behavioral and transactional data. Access to ESP/advertising platforms where modeled audiences can be activated. Feature/hypotheses and model input alignment - defined "active" vs "inactive" criteria (e.g., days since last purchase or session). Dialogue/Experience ownership: access to front-end / design support for customizing styling and layout of winback dialogues. Clear understanding of business objective, success metrics.',
  'Discovery: 2 wks, Implementation: 6 wks (AIWB notebook for training churn model, 2 Dialogues - PS built OR 2 Experiences - Customer built), Go-Live: 1 wk, Total: ~9 wks. Future: OOTB AIWB notebooks to train propensity to churn models and AI builder for Experiences can potentially reduce TTV to <6 wks.',
  true
),
(
  'Loyalty Tier Progression',
  'Loyalty & Advocacy',
  'When customers participate in my loyalty program, I want to personalize incentives and surface progress meaningfully so I can increase participation and repeat purchase frequency.',
  'Web, Mobile App',
  'Experience (XP), Dialogue, Connection, AIWB, Listeners, Segments',
  'Incremental LTV growth: % increase in LTV among loyalty program members influenced by BlueConic''s agentic orchestration, compared to a historical baseline or control group',
  'Loyalty tier rate, Tier advancement rate, Repeat purchase frequency',
  'No OOTB connections with common loyalty platforms like Smile.io, Annex Cloud, Talon.One. No pre-trained, loyalty-specific NBA models available for picking the best personalized offer to serve. Number of Dialogues/Experiences - need to decide on whether to include the Dialogue/Experience build in the onboarding or to push ownership to the customer. Either way - availability of copy/styling can cause delay.',
  'Templatized solution for loyalty-specific NBA. Internal team or agency resource dedicated to building and testing NBA Dialogues/Experiences (XP).',
  'Templatized AIWB notebook for training loyalty-specific NBA model. Standardized feature sets, data model, data collection, dashboard. Pre-configured, click-to-clone templates for Loyalty-related Dialogues/Experiences, e.g. current point balances and tier progress ("You''re only 150 points away from Gold!"), next reward unlocks or exclusive offers for higher tiers, Referral program prompts for loyal advocates. Standardized customer data schema and Listeners setup designed for Loyalty use cases. Purpose-built Connections for top Loyalty Platforms for ingesting loyalty data like points balance and loyalty status or tier.',
  'Access to Loyalty platforms for importing loyalty balance, status, etc. Dialogue/Experience (XP) ownership: access to front-end / design support for customizing styling and layout of winback dialogues. Engagement Rules- defined tier thresholds, rewards logic, and promotional cadence. Clear understanding of business objective, success metrics.',
  'Initial implementation (no NBA): Discovery: 1 wks, Implementation: 5 wks (3 Dialogues, PS-built OR 2 Experiences Customer-built), Go-Live: 1 wk, Total: ~7 wks. Future: OOTB Loyalty platform connectors can potentially reduce TTV to <4 wks. NBA add-on: Discovery: 2 wks, Implementation: 4 wks, Go-Live: 1 wk, Total: ~7 wks. Future: OOTB AIWB notebooks to train NBA models can potentially reduce TTV for the NBA-addon to <5 wks.',
  true
),
(
  'Dormant Customer Reactivation',
  'Loyalty & Advocacy',
  'When customers haven''t purchased in a while, I want to re-engage them with relevant content or offers so I can revive inactive shoppers and restore their purchase frequency.',
  'Web, App Push, Mobile App, SMS/Whatsapp/Messages, Email, Ads, Social, Display',
  'Dialogues, XP, Connections, AIWB, Segments, Listeners',
  'Reactivated Customer Revenue: Revenue generated from previously dormant customers who were reactivated through BlueConic''s agentic orchestration, compared to a historical baseline or control group',
  'Reactivation Rate, CPA',
  'No pre-trained models available for propensity to reengage. Number of Dialogues/Experiences - need to decide on whether to include the Dialogue build in the onboarding or to push ownership to the customer. Either way - availability of copy/styling can cause delay.',
  'Templatized solution for propensity to reengage. Internal team or agency resource dedicated to building and testing NBA Dialogues/Experiences (XP).',
  'Templatized AIWB notebook for training propensity to reengage model. Standardized feature sets, data model, data collection, dashboard. Pre-configured, click-to-clone templates for reengagement Dialogues/Experiences, e.g. discounts, reminders, loyalty prompts. Standardized customer data schema and Listeners setup designed for Dormant customers use cases. Purpose-built Connections to common ecommerce platforms (Shopify, Magento, Salesforce Commerce Cloud) and ESPs (SFMC, Braze, MailChimp) for transactional and engagement data sync.',
  'Data readiness -Transactional and email/app engagement data. Feature/hypotheses alignment for propensity to reengage modeling. Access to ESP where modeled audiences can be activated. Dialogue/Experience ownership - access to front-end / design support for customizing styling and layout of winback dialogues. Reactivation Strategy - defined incentive and messaging framework (discounts, reminders, loyalty prompts). Clear understanding of business objective, success metrics.',
  'Discovery: 2 wks, Implementation: 7 wks (AIWB notebook for training propensity to reengage model, 2 Dialogues - PS built), Go-Live: 1 wk, Total: ~9 wks. Future: OOTB AIWB notebooks to train propensity to reengage models can potentially reduce TTV to <6 wks.',
  true
),
(
  'Advocacy & Referral',
  'Loyalty & Advocacy',
  'When customers are satisfied, I want to prompt and reward advocacy so I can grow through referrals and strengthen brand trust.',
  'Web',
  'Dialogues, XP, Connections, AIWB, Segments, Listeners',
  'Incremental Referral Revenue: The incremental revenue generated from new customers acquired through BlueConic''s agentic orchestration associated with advocacy and referral programs, compared to a historical baseline or standard referral performance',
  'Referral rate, CPA, NPS',
  'No OOTB connections with common referral program platforms like Mention Me, Friendbuy, Yotpo, or Talkable. Number of Dialogues/Experiences - need to decide on whether to include the Dialogue/Experience build in the onboarding or to push ownership to the customer. Either way - availability of copy/styling can cause delay.',
  'Templatized solution for referral/advocacy use case. Internal team or agency resource dedicated to building and testing NBA Dialogues/Experiences (XP).',
  'Pre-configured, click-to-clone templates for referral/advocacy-related Dialogues/Experiences, e.g. to be used immediately after a successful purchase or positive review, following a loyalty milestone or reward redemption and within an onboarding or post-delivery email flow. Standardized customer data schema and Connections/Listeners setup designed for referral/advocacy use cases; specifically to collect behavioral, transactional, and sentiment data to identify potential advocates. Purpose-built Connections for top Loyalty Platforms for ingesting loyalty data like points balance and loyalty status or tier.',
  'Data readiness - Behavioral, transactional, and sentiment data. Incentive Framework - Defined referral rewards (discounts, loyalty points, credits) and eligibility logic. Access to a referral program partner or internal API endpoint for referral tracking. Dialogue/Experience ownership: access to front-end / design support for customizing styling and layout of referral/advocacy dialogues. Clear understanding of business objective, success metrics.',
  'Discovery: 1 wks, Implementation: 4 wks (2 Experiences, customer-built), Go-Live: 1 wk, Total: ~6 wks. Future: AI Experience Builder can potentially reduce Implementation time, no data available yet to estimate impact',
  true
),
(
  'AI Assistant Discovery Presence',
  '',
  'When customers use AI assistants to explore products, I want my brand''s offers and content to appear intelligently in those interactions so I can capture demand in new discovery channels.',
  'Web, Social, Ads, Display, QR Code',
  'MCP Server',
  'Incremental Assistant-Attributed Revenue: Incremental revenue generated from sessions initiatied by external AI assistants that consume the MCP endpoint, vs baseline or control group',
  'Views, Click Through Rate, Newsletter subscribers',
  'TBD',
  'TBD',
  'MCP Server / API for Product & Offer Exposure - can serve as a real-time content and offer distribution layer, exposing: product catalogs and promotion feeds, loyalty or referral offers tied to customer profiles, contextual creative variants for advocate or referral journeys.',
  'TBD',
  'TBD',
  true
),
(
  'Predictive Replenishment & Stock-Aware Upsell',
  'Post Purchase Growth',
  'When customers are likely to run out of a product or when stock levels shift, I want to automatically prompt the right replenishment or upsell offer so I can increase repeat purchases and prevent lost sales due to poor timing or availability.',
  'Web, Email, Push, SMS/Whatsapp/Messages, Mobile App, Connections (i.e. loyalty platform)',
  'Dialogue, Connection, Product Recommendations, Product Store, AI WB',
  'Repeat Purchase Rate Uplift: % increase in customers who make a repeat purchase within a predicted reorder window due to BlueConic''s agentic orchestration features, compared to a historical baseline or control group',
  'Repurchasing rate, AOV, CLV',
  'No pre-trained models available for next best product (NBP) or predictive replenishment. Product store limits - can only store up to 20k items. Number of product recommendation dialogues and emails - need to decide on whether to include the recommendation Dialogue and email build in the onboarding or to push ownership to the customer. Either way - availability of copy/styling can cause delay.',
  'Templatized solutions for the NBP and predictive replenishment. Internal team or agency resource dedicated to building and testing Product Recommendation Dialogues.',
  'Agentic-based Next Best Offer model support in recommendations. Increase limit on number of content/product store items. Templatized AIWB notebooks for training models to predict next best product (NBP). Standardized feature sets, data model, data collection, dashboard. Pre-configured, click-to-clone templates for Product Recommendation Dialogues and Emails, e.g. "Back in stock" or personalized upsell recommendations at checkout ("Add these for 20% off"), dynamic recommendations in product detail pages. Standardized customer data schema and Listeners/Connections setup designed for product upsell use cases.',
  'Data readiness - consistent website tagging to support capturing product data or having a product feed available on SFTP. Dialogue ownership: access to front-end / design support for customizing styling and layout of recommendation units. Feature/hypotheses alignment & Modeling Readiness for NBP model - defined product categories, known conversion events, and sufficient transaction data. Clear understanding of product store limits, business objective, success metrics.',
  'Discovery: 2 wks, Implementation: 7 wks (AIWB notebook for training NBP model, 2 Dialogues - PS built), Go-Live: 1 wk, Total: ~10 wks. Future: OOTB AIWB notebooks to train NBP models can potentially reduce TTV to <6 wks.',
  true
);